export const ENDPOINTS = {
  authLogin: '/auth/login/step-1',
  authVerifyOtp: '/auth/login/step-2',
  profile: '/admin/profile',
  dashboardKpis: '/admin/dashboard/kpis',
  loginAlerts: '/admin/login-alerts',
  loginAlertsStats: '/admin/login-alerts/stats',
  generalAdmins: '/admin/general-admins',
  superAdmins: '/admin/super-admins',
  departmentAdmins: '/admin/department-admins',
  adminRolesDropdown: '/admin/roles/dropdown',
  admins: '/admin/admins',
  adminPermissions: '/admin/permissions',
  staff: '/admin/staff',
  users: '/admin/users',
  categories: '/admin/categories',
  departments: '/admin/departments',
  categorySchemas: '/admin/category-schemas',
  rbos: '/admin/rbos',
  products: '/admin/products',
  services: '/admin/services',
  bookings: '/admin/bookings',
  approvalOverrides: '/admin/approval-overrides',
  masterAnalytics: '/admin/analytics',
  contactViews: '/admin/reports/contact-views',
  auditLogs: '/admin/reports/audit-logs',
  activityLog: '/admin/activity-log',
  platformSummary: '/admin/reports/platform-summary',
  reportOverview: '/admin/reports/overview',
  reportBookings: '/admin/reports/bookings',
  reportProducts: '/admin/reports/products',
  reportRbos: '/admin/reports/rbos',
  reportCustomers: '/admin/reports/customers',
  reviewsModeration: '/admin/reviews',
  supportConversations: '/admin/support/conversations',
  dealDeskInquiries: '/admin/deal-desk/inquiries',
  notifications: '/admin/notifications',
  settings: '/admin/settings',
  roles: '/roles/groups',
  rolePermissionsAssign: '/roles/group-permissions',
  permissionsList: '/roles/permissions',
} as const;

export type EndpointKey = keyof typeof ENDPOINTS;
